### ISSUE TITLE
Cannot build on Ubuntu 14.04.1 LTS.

### ISSUE THREAD

**Issue by nethomas1968** [kivy/kivy-remote-shell#5]
Fails to build using:
./distribute.sh -m 'openssl pycrypto pyasn1 pyjnius twisted kivy'

It gets to the pycrypto module but fails to build due to missing #include files.
For example:

compilation terminated.
In file included from cryptlib.c:117:0:
cryptlib.h:62:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>

Any ideas?

**Comment by akshayaurora** [comment]
Instructions and code updated, re-open if you still have this issue with bulldozer and new toolchain.
